# Generated by Django 3.0.7 on 2023-04-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20230209_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
