# Generated by Django 3.0.7 on 2023-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20230401_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost_per_item',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
