# Generated by Django 3.0.7 on 2023-08-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20230810_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
